### PR TITLE
#45 - Push a Docker image to Amazon ECR repository

### LINKED ISSUE #45: COM04-AWS100 - Push a Docker image to Amazon ECR repository
### Choose the Cloud Service Provider (Please only choose one, unless its multi-cloud, delete the remaining)
- Amazon Web Services

### Choose the level of difficulty (Please only choose one, delete the remaining)
- Level 100 (Introductory)

### Choose the category (Please only choose one, delete the remaining)
- Cloud Computing (COM)

### Calculate the estimated time required to complete this project (Rather go with more if unsure)
- 30 minutes

### PR DESCRIPTION
**Pull request by johanrin**
I created this project and edited the README file.

### CODE REVIEW

**Comment by what-name** [comment]
- Project has no typos and it has great references for the current objectives
- I'm not sure if creating the Docker image itself should be included or not. For participants that already know well how to build Docker images, this project is perfect. However for ones that don't have experience building images or don't know what they are, it's a bit confusing. Especially given that it's a Level100, which technically it is. With a bit more info and guidance, this can pass as 100 easily.
- What about adding an extra section with `Prerequisites: A self-built Docker image`?
- We could add an extra resource ["How to build a Docker image"](https://www.youtube.com/watch?v=6Er8MAvTWlI) for example (this is an amazing tutorial).
- Time to complete only applies if participant has a ready-to-go Docker image built, I think this should be declared.

This is such a catch-22. It is Level 100 from the AWS side, but only if you know how to build Docker images, which is not necessarly a Level 100 topic overall.

**Review by what-name — CHANGES_REQUESTED** [review]
- Project has no typos and it has great references for the current objectives
- I'm not sure if creating the Docker image itself should be included or not. For participants that already know well how to build Docker images, this project is perfect. However for ones that don't have experience building images or don't know what they are, it's a bit confusing. Especially given that it's a Level100, which technically it is. With a bit more info and guidance, this can pass as 100 easily.
- What about adding an extra section with `Prerequisites: A self-built Docker image`?
- We could add an extra resource ["How to build a Docker image" ](https://www.youtube.com/watch?v=6Er8MAvTWlI)for example (this is an amazing tutorial).
- Time to complete only applies if participant has a ready-to-go Docker image built, I think this should be declared.


This is such a catch-22. It is Level 100 from the AWS side, but only if you know how to build Docker images, which is not necessarly a Level 100 topic overall.

**Comment by johanrin** [comment]
Thanks for your feedback @what-name! I edited the project with your comments.

**Review by what-name — APPROVED** [review]
Nice! Looks great to me.

**Pull request merged**
