### PR TITLE
#27 - Edit issue labeler and add cloud provider label

### LINKED ISSUE #27: Adding cloud provider labels
**Is your feature request related to a problem? Please describe.**
Adding labels for cloud providers

**Describe the solution you'd like**
Add AWS,GCP and Azure to labeler.yml

**Additional context**

label

### PR DESCRIPTION
**Pull request by johanrin**
I edited the labeler and added cloud provider labels.

### CODE REVIEW

**Comment by what-name** [comment]
See #35 
Issue template should be updated to use full names of CSPs instead of abbreviations. Current labeler is looking for abbreviations.

**Comment by what-name** [comment]
After merge of #39, update regex for CSPs and this can be merged as well.

**Comment by johanrin** [comment]
@what-name Here is the modification I planned to do. Is it ok for you?
```
AWS:
  - "(- Amazon Web Services)"
Azure:
  - "(- Microsoft Azure)"
GCP:
  - "(- Google Cloud Platform)"
```

**Comment by madebygps** [comment]
@what-name Looks good to me, thoughts?

**Comment by what-name** [comment]
- I'd add "Other" just to future proof it. There's also another "Other" text for the category, but it might also be good if that gets the same label so it stands out more. "Other" is in the list of Cloud Providers in the [project idea issue template](https://github.com/100DaysOfCloud/100DaysOfCloudIdeas/blob/master/.github/ISSUE_TEMPLATE/cloud-project-idea.md).
- Google Cloud does not have "Platform" after it in the issue template.

Besides these, it looks great to me too

```
AWS:
  - "(- Amazon Web Services)"
Azure:
  - "(- Microsoft Azure)"
GCP:
  - "(- Google Cloud)"
Other:
  - "(- Other)"
```

**Comment by johanrin** [comment]
@what-name I'm sure the user will delete the "Other" tag especially with sentences like these:
- Other (Please specify)
- Other (Please specify so we can add a category)

I think we should edit the template by something like this:
- Other: \<specify the cloud service provider\>
- Other: \<specify the category\>

**Comment by madebygps** [comment]
@johanrin merged, should be good to make your changes :)

**Comment by johanrin** [comment]
Done!

**Review by what-name — APPROVED** [review]
Nice

**Pull request merged**
